import type { Metadata } from "next";
import "./globals.css";
import { bricolage } from "@/lib/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${bricolage.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
